[project]
name = "simulatability-shortcut"
version = "0.1.0"
requires-python = ">=3.11,<3.13"

# result notebooks only
dependencies = [
    "ipykernel",
    "matplotlib",
    "notebook",
    "numpy",
    "pandas",
    "scipy",
]

# get explanations and make generation
[project.optional-dependencies]
generation = [
    "datasets",
    "interpreto==0.5.0",
    "nnsight==0.7.0",
    "torch",
    "tqdm",
    "transformers",
]
vllm = ["vllm"]
