[project]
name = "simulatability-shortcut"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "torch==2.11.0+cu126",
    "datasets",
    "git+https://github.com/FOR-sight-ai/interpreto.git@concepts-refacto",
    "transformers",
    "tokenizers==0.22",
    "tqdm",
    "ipykernel",
    "pandas",
]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

# UV_HTTP_TIMEOUT=300 uv pip install --prerelease=allow -e .
