[project]
name = "simulatability-shortcut"
version = "0.0.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "datasets",
    "interpreto",
    "transformers",
    "tokenizers==0.22.2",
    "tqdm",
    "ipykernel",
    "pandas",

    # Do not pin torch manually. Let vLLM resolve the compatible torch build.
    "torch",

    # Nightly required for Qwen3.5 support.
    "vllm",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
vllm = { index = "vllm-nightly" }

[[tool.uv.index]]
name = "vllm-nightly"
url = "https://wheels.vllm.ai/nightly"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

# UV_HTTP_TIMEOUT=300 uv sync --reinstall --prerelease=allow
